#!/bin/csh
#SBATCH --job-name=settle_seed_1_susc_03_6_field_20_0
#SBATCH --nodes=1
#SBATCH --ntasks=30
#SBATCH --oversubscribe
#SBATCH --time 08:00:00
#SBATCH --mail-user sikka@umd.edu
#SBATCH --mail-type=ALL

#############################################################
# change the below input variable to your own filename
#############################################################


set dir=/scratch/zt1/project/hartzell-lab/user/sikka/SIMS-LIGGGHTS/avalanching_experiments/mag_steel_sims/MDM_sims/seed_1/susc_03_6/field_20_0
set codeexe=/scratch/zt1/project/hartzell-lab/user/sikka/SIMS-LIGGGHTS/avalanching_experiments/lmp_auto

cd $dir
# rm -r -f output_settle.txt
# rm -r -f results_steel_mag
module load openmpi
module load eigen
module load boost
mpirun -np 30 $codeexe -echo both -i ./in.settle > ./output_settle.txt
